# Build Swift for WASM to verify the WebGPU WASM backend compiles.

name: Build (WASM - Embedded)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build (WASM - Embedded)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Read Swift version
        id: swift-version
        run: echo "version=$(cat .swift-version)" >> "$GITHUB_OUTPUT"

# setup-swift can install "main-snapshot" but fails in the version comparison check, cause it compares "main-snapshot" to "6.4"
# therefore we install the main-snapshot manually with swiftly below
      - uses: swift-actions/setup-swift@v3
        with:
          swift-version: "${{ steps.swift-version.outputs.version }}"
          skip-verify-signature: true

      - name: Check Swift version
        run: swift --version

      - name: Install main-snapshot Swift Toolchain
        run: swiftly install --use main-snapshot --assume-yes

      - name: Check Swift version again
        run: swift --version

      - name: Install Swift WASM SDK
        run: make sdk-install

      - name: Build WebGPU (Embedded)
        run: |
          swiftly install --use main-snapshot --assume-yes
          swift --version
          make wasm-build SWIFT_MODE=embedded

      - name: Build BitonicSort (Embedded)
        run: |
          swiftly install --use main-snapshot --assume-yes
          swift --version
          make wasm-build-bitonic SWIFT_MODE=embedded
